name: VANTA Kernel Protocol Scheduler

description: |
  Scheduled tasks and protocol integrity checks for VANTA Kernel symbolic + narrative system

on:
  schedule:
    - cron: '0 3 * * *' # Run daily at 3AM UTC
  push:
    branches:
      - main

jobs:
  update-protocol-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install requirements if the file exists, otherwise skip
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          else
            echo "requirements.txt not found, skipping installation."
          fi
          # Ensure PyYAML is installed for the compliance script if not in requirements
          python -m pip install PyYAML
      - name: Update Protocol Registry
        run: |
          echo "Running script to update protocol registry..."
          export PYTHONPATH=.
          python scripts/update_protocol_registry.py
      - name: Protocol Compliance Check
        run: |
          echo "Running protocol compliance check..."
          export PYTHONPATH=.
          python scripts/check_protocol_compliance.py

  generate-rl-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Generate RL Training Labels
        run: |
          python scripts/generate_rl_labels.py

  commit-graph-health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Commit Graph Health
        run: |
          git fsck
          git log --graph --oneline --all
          echo "Commit graph integrity checked." 